#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = Life

PROJECTVERSION = 2.6
PROJECT_TYPE = Application
LANGUAGE = English

NEXTSTEP_APPICON = life.tiff
NEXTSTEP_DOCICONS = life.doc.tiff

ICONSECTIONS =	-sectcreate __ICON app life.tiff \
		-sectcreate __ICON life.doc life.doc.tiff

LOCAL_RESOURCES = InfoPanel.nib Life.nib Preferences.nib Random.nib\
                  Help

GLOBAL_RESOURCES = CLear.tiff Isotropic.tiff life.doc.tiff life.tiff\
                   run.tiff Step.tiff StepForward.tiff stop.tiff\
                   Info.life LifeSamples

CLASSES = Generator.m InfoGenerator.m InfoLifeView.m LifeView.m\
          PrefController.m RandomGenerator.m

HFILES = Generator.h InfoGenerator.h InfoLifeView.h LifeView.h\
         PrefController.h RandomGenerator.h

MFILES = Life_main.m

PSWFILES = LifeChar.psw

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = app.make
NEXTSTEP_INSTALLDIR = $(HOME)/Apps
WINDOWS_INSTALLDIR = $(HOME)/Apps
PDO_UNIX_INSTALLDIR = $(HOME)/Apps
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


FRAMEWORKS = -framework Foundation -framework AppKit


include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
