#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = Life

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = life.tiff
DOCICONS = life.doc.tiff

LOCAL_RESOURCES = InfoPanel.nib Life.nib Preferences.nib Random.nib\
                  Help

GLOBAL_RESOURCES = CLear.tiff Isotropic.tiff life.doc.tiff life.tiff\
                   run.tiff step.tiff Step.tiff stop.tiff Info.life\
                   LifeSamples

CLASSES = Generator.m InfoGenerator.m InfoLifeView.m LifeView.m\
          PrefController.m RandomGenerator.m

HFILES = Generator.h InfoGenerator.h InfoLifeView.h LifeView.h\
         PrefController.h RandomGenerator.h

MFILES = Life_main.m

PSWFILES = LifeChar.psw

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app life.tiff \
		-sectcreate __ICON life.doc life.doc.tiff

LIBS = -lMedia_s -lNeXT_s -lIndexing_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
